services:
  next-app:
    container_name: vasiliy-app
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3010:3010
    env_file:
      - .env.local
    networks:
      - pg_apps

networks:
  pg_apps:
    external: true
